
# Install packages
if (!"forcats" %in% installed.packages()) install.packages("forcats", dependencies = T)
if (!"ggplot2" %in% installed.packages()) install.packages("ggplot2", dependencies = T)
if (!"knitr" %in% installed.packages()) install.packages("knitr", dependencies = T)
if (!"lme4" %in% installed.packages()) install.packages("lme4", dependencies = T)
if (!"lmerTest" %in% installed.packages()) install.packages("lmerTest", dependencies = T)
if (!"lsmeans" %in% installed.packages()) install.packages("lsmeans", dependencies = T)
if (!"multcomp" %in% installed.packages()) install.packages("multcomp", dependencies = T)
if (!"multcompView" %in% installed.packages()) install.packages("multcompView", dependencies = T)
if (!"pastecs" %in% installed.packages()) install.packages("pastecs", dependencies = T)
if (!"readxl" %in% installed.packages()) install.packages("readxl", dependencies = T)
if (!"robustlmm" %in% installed.packages()) install.packages("robustlmm", dependencies = T)
if (!"shadowtext" %in% installed.packages()) install.packages("shadowtext", dependencies = T)
if (!"svglite" %in% installed.packages()) install.packages("svglite", dependencies = T)
if (!"tidyverse" %in% installed.packages()) install.packages("tidyverse", dependencies = T)

# Load packages
library(forcats)
library(ggplot2)
library(knitr)
library(lme4)
library(lmerTest)
library(lsmeans)
library(multcomp)
library(multcompView)
library(pastecs)
library(readxl)
library(robustlmm)
library(shadowtext)
library(svglite)
library(tidyverse)
